### ISSUE TITLE
Please explain how this application is working ?

### ISSUE THREAD

**Issue by Apurva1590** [edniemeyer/discsCatalog#2]
Hello Eduardo, 

This is awesome application and as I am learning MEAN  with Elasticsearch this is really a great example. 

As I am newbie to this can you please explain theoretically how this application is working end to end ?

This would be a great help.

Thank you in advance 

Regards 
Apurva

**Comment by edniemeyer** [comment]
Hello! If I'm not mistaken, I've followed this tutorial to develop: https://thinkster.io/tutorials/mean-stack. Feel free to add comments on the code to help other people and push it here.

Regards
Eduardo
